from .all_companies import CompaniesView
from .activity import ActivityView
from .categories import CategoriesView
from .home import HomeView
from .login import LoginView
from .logout import LogoutView
from .registration import RegistrationView
from .about import AboutView
from .company import CompanyView
